name: Build Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # AZURE_CREDENTIALS_CLIENT: '{"clientId":"${{ vars.CLIENT_ID }}","clientSecret":"${{ vars.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ vars.TENANT_ID }}"}'           
  ACRName: 'vars.ACRName'
  ACRImageName: '$(vars.AppName)'
  ACRImageTag: '$(Build.BuildId)'
  ACRFullName: '$(vars.ACRName).azurecr.io'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v4
    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACRFullName }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build the image and push it to ACR
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.ACRFullName }}/${{ env.ACRImageName }}:1 
        file: ./Dockerfile
