# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - appwsdocker3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrwsdocker3.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a4b41c7519e34e62af6b064f80e8b5d1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3d02068d97e84599b7d854fc99a8590f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrwsdocker3.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a4b41c7519e34e62af6b064f80e8b5d1 }}/nginx-react:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'appwsdocker3'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ab2e2fafea5d4664a3bb0a94726a6c21 }}
        images: 'acrwsdocker3.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a4b41c7519e34e62af6b064f80e8b5d1 }}/nginx-react:${{ github.sha }}'